# Generated by Django 4.2.26 on 2025-11-20 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.TextField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='{}')),
                ('page_type', models.CharField(choices=[('normal', 'Normal'), ('wiki', 'Wiki'), ('database', 'Database')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
