# Generated by Django 4.2.26 on 2025-11-20 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
        ('pages', '0002_page_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='databases.database'),
        ),
    ]
