# Generated by Django 4.2.26 on 2025-12-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_user_organization'),
        ('pages', '0004_page_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.organization'),
        ),
    ]
