# Generated by Django 4.2.26 on 2026-02-24 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_space_members_alter_space_organization_spacetype_and_more'),
        ('pages', '0006_rename_company_to_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='crm.space'),
        ),
    ]
