# Generated by Django 4.2.26 on 2026-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='github_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
