# Generated by Django 4.2.26 on 2025-11-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
