# Generated by Django 4.2.26 on 2025-12-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_sharedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='allow_task_creation',
            field=models.BooleanField(default=False),
        ),
    ]
