# Generated by Django 4.2.26 on 2025-12-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_sharedlink_allow_task_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='allow_document_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='allow_meeting_creation',
            field=models.BooleanField(default=False),
        ),
    ]
