# Generated by Django 4.2.26 on 2025-12-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_sharedlink_allow_document_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for guest access', max_length=128, null=True),
        ),
    ]
