# Generated by Django 4.2.26 on 2025-12-30 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_address_billing_and_more'),
        ('crm', '0012_sharedlink_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='EditorJS content'),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, default=dict, help_text='EditorJS structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='core.organization')),
            ],
        ),
    ]
