# Generated by Django 4.2.26 on 2026-02-24 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_address_billing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0015_rename_company_to_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='core.organization'),
        ),
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('has_contracts', models.BooleanField(default=False)),
                ('has_meetings', models.BooleanField(default=True)),
                ('has_documents', models.BooleanField(default=True)),
                ('has_tasks', models.BooleanField(default=True)),
                ('has_contacts', models.BooleanField(default=True)),
                ('vocabulary', models.JSONField(blank=True, default=dict, help_text="e.g. {'contact': 'Membre'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_types', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='crm.spacetype'),
        ),
    ]
