# Generated by Django 4.2.26 on 2026-02-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text="Stores change deltas like {'old_status': 'draft', 'new_status': 'signed'}"),
        ),
    ]
