# Generated by Django 4.2.26 on 2026-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_activitylog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='github_repo',
            field=models.CharField(blank=True, help_text='Format: owner/repo', max_length=255, null=True),
        ),
    ]
