# Generated by Django 4.2.26 on 2025-12-30 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_organization_address_billing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_model', models.CharField(choices=[('task', 'Task'), ('contract', 'Contract')], max_length=50)),
                ('trigger_event', models.CharField(choices=[('create', 'Created'), ('update', 'Updated')], max_length=50)),
                ('condition_field', models.CharField(blank=True, help_text="Field to check, e.g., 'status'", max_length=100)),
                ('condition_value', models.CharField(blank=True, help_text="Value to match, e.g., 'done'", max_length=100)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('create_task', 'Create Task')], max_length=50)),
                ('action_config', models.JSONField(default=dict, help_text='Configuration for the action (recipient, templates, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.organization')),
            ],
        ),
    ]
