# Generated by Django 4.2.26 on 2025-12-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrule',
            name='action_config',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='condition_field',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='condition_value',
        ),
        migrations.AddField(
            model_name='automationrule',
            name='actions',
            field=models.JSONField(default=list, help_text='List of actions to execute'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text='List of conditions (AND logic)'),
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Log details or error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
