# Generated by Django 4.2.26 on 2025-11-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_database'),
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='parent_page',
        ),
        migrations.AddField(
            model_name='database',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database_schema', to='pages.page'),
        ),
    ]
