# Generated by Django 4.2.26 on 2025-11-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_remove_database_parent_page_database_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('relation', 'Relation')], default='text', max_length=20),
        ),
    ]
