# Generated by Django 4.2.26 on 2025-12-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address_billing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible user-defined fields'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='siret',
            field=models.CharField(blank=True, help_text='Registration Number', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
